version: '3.9'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: kyp
    ports:
      - 5432:5432
    volumes:
      - ./data-persistence/postgres:/var/lib/postgresql/data