import 'bootstrap/dist/css/bootstrap.min.css'
import '../global.css';
import React from 'react';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
export const metadata = {
  title: 'KYP',
  description: 'Generated by create-nx-workspace',
};

export default function BaseLayout({ children }) {
  return (
    <html lang="en">
    <body>
    <Header />
    {children}
    <Footer />
    </body>
    </html>
  );
}
