import 'bootstrap/dist/css/bootstrap.min.css'
import './global.css';
import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
export const metadata = {
  title: 'Welcome to app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
